[package]
name = "htm-runtime"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
gpu-renderer = ["dep:vello"]

[dependencies]
anyrender.workspace = true
anyrender_vello_cpu.workspace = true
blitz-dom.workspace = true
blitz-html.workspace = true
blitz-paint.workspace = true
blitz-traits.workspace = true
cssparser.workspace = true
kurbo.workspace = true
peniko.workspace = true
png.workspace = true
selectors.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
skrifa.workspace = true
stylo.workspace = true
stylo_traits.workspace = true
url.workspace = true
vello = { workspace = true, optional = true }
