[package]
name = "htm-shell-host"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
gpu-renderer = [
    "htm-runtime/gpu-renderer",
    "wayland-client/system",
]

[dependencies]
dbus.workspace = true
htm-runtime = { path = "../htm-runtime" }
jiff.workspace = true
memmap2.workspace = true
pipewire.workspace = true
rustix = { workspace = true, features = ["event", "time"] }
serde.workspace = true
serde_json.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true
